### ISSUE TITLE
Make sure first line show completely on window after scrolling?

### ISSUE THREAD

**Issue by liebkne** [jdtsmith/ultra-scroll-mac#2]
Hi,

I notice some performance issue when the first line on window are not shown completely after some scrolling by trackpad, like this

<img width="237" alt="Screenshot 2024-01-09 at 23 50 36" src="https://github.com/jdtsmith/ultra-scroll-mac/assets/5475262/0a4a67f2-b1a7-4393-a8f4-2f6d9dc63714">

compared to
<img width="233" alt="Screenshot 2024-01-09 at 23 50 43" src="https://github.com/jdtsmith/ultra-scroll-mac/assets/5475262/3bbd7b8a-5096-4d4f-b266-da0997479f72">

In the first situation, scrolling using keyboard like <kbd>ctrl-v</kbd> cause noticeable laggy. One can validate it by open `org.el` and keep pressing <kbd>ctrl-v</kbd> on that first situation. 

In the second situation, no issue is observed and scrolling by keyboard is as fast and smooth as by trackpad.

**Comment by jdtsmith** [comment]
Are you sure you are up to date?  I fixed something like this a month ago; it should snap to the top or bottom when you scroll to the end.  This package doesn't influence `C-v` based scrolling, so you must be doing something else there (pixel scroll mode?).  Please see if this issue reproduces with `/Applications/Emacs.app/Contents/MacOS/Emacs -Q` and report back.

**Comment by liebkne** [comment]
Hi, thanks for you help. After some binary debugging, I found the issue. I have the following setting stolen from doom emacs to improve scrolling performance long times ago

```
(setq auto-window-vscroll t)
```

Because the scrolling by trackpad can stop at any position of a line, this becomes an issue for the following commands like <kbd>C-v</kbd>. Nevertheless it's not really an issue of `ultra-scroll-mac`. Thanks for the great package!
