### ISSUE TITLE
Scrolling stuck on line when slowly scrolling

### ISSUE THREAD

**Issue by everydayanchovies** [jdtsmith/ultra-scroll-mac#3]
When slowly scrolling (inching upwards) in an org document with babel, latex and whatnot, the point wouldn't move past some lines.

I apologize for the vague issue, but I have not idea how to profile this, but I will respond if you have any suggestions.

For what it's worth, when merging pixel-scroll-precision-mode with Mitsuharu's, I observe no issues at all. 
See my write-up at https://maximzuriel.nl/physics-and-code/emacs-mac-smooth-scroll/article.
It is not even necessary to coalesce the events, but I left that there just in case.

**Comment by jdtsmith** [comment]
Does it get stuck on lines starting with invisible characters like hidden org markup?  Does it have inline images (like latex preview)? This was an emacs bug.

**Comment by jdtsmith** [comment]
Ps: it would be worth pointing to my package from your post.  It's very challenging to scroll past images at any speed and it can be accidentally correct for some situations.

**Comment by everydayanchovies** [comment]
Good to hear that the issue is being tracked, I posted a link on the bottom of my blog post.
When I get time later this week, I'll do more extensive testing.

**Comment by everydayanchovies** [comment]
I tested it on a fundamental buffer and made a video of the getting stuck.

I show the behavior in an elisp mode buffer, but I tested it on a fundamental buffer after making the video.


https://github.com/jdtsmith/ultra-scroll-mac/assets/4356678/107d6615-58fc-4a0f-aa2b-f6fd524c10a0

**Comment by jdtsmith** [comment]
Thanks, that shouldn't be happening.  If you widen the window to avoid the line wrap, does it still happen?

**Comment by everydayanchovies** [comment]
yes unfortunately

**Comment by jdtsmith** [comment]
Strange, I don't see this (with or without wrap).  I've applied a few fixes to my emacs-mac that fixed various display bugs, but they all relate to inline images, and I see none of those here.  You definitely have `scroll-conservatively=101`, right?  This is essential as mentioned in the INSTALL.

**Comment by everydayanchovies** [comment]
Yes I have scroll-conservatively=101.

I am interested in your fixes if you would like to share them.

Since I don't see a way to easily debug this, maybe let's wait for more people to chime in?
Just having this bug report searchable might be nice for anyone effected.

**Comment by jdtsmith** [comment]
You don't _also_ have `pixel-scroll[-precision]-mode` enabled by chance?  Can you try this from `emacs -Q` loading only `ultra-scroll-mac` and see how that goes?

**Comment by jdtsmith** [comment]
You can see the fixes (Eli's, not mine) at the following bug reports:

- [**Bug 67333**: Trapped by invisible characters](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=67333) (no response yet, workaround applied in USM).
- [**Bug 67533**: inline images lead to pixel position issues](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=67533) (patches applied to emacs master).
- [**Bug 67604**: inline images lead to motion problems](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=67604) (not yet fixed, but reproduced with included script). 

Do any of these look valid for your buffer?

**Comment by jdtsmith** [comment]
I did also just noticed your comments (and more) are in a proportional font.  Can you try disabling that?

**Comment by everydayanchovies** [comment]
Since emacs -Q did not have this issue, I looked at all scroll related variables that I ever changed and reset them to their default values in my fully loaded config (with proportional fonts and all).

The issue is only present when scroll-margin > 0.

For completeness, these are my troublesome values

`(setq scroll-margin 2
      scroll-conservatively 101
      fast-but-imprecise-scrolling t
      scroll-preserve-screen-position t)`

Does that let you reproduce this issue?

Thanks for the links!

**Comment by jdtsmith** [comment]
Oh yes indeed, `scroll-margin>0` is highly verboten.  That basically adds two lines top and bottom where if point ever lands there, emacs redisplay will "helpfully" recenter that line in the window.  

Added a bit to the docs.  Longer term I've thought about setting these scroll variables to their required values on scroll start and resetting them on scroll stop, but you'd _still_ have to find somewhere "safe" to put point.
